env:
    APP_VERSION: 0.0.${{github.run_number}}
    RELEASE_PATH: ${{github.action_path}}/release
    
name: "Publish Release v${{env.APP_VERSION}}"

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Configurator

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Publish
      run: "dotnet publish ./Configurator/Configurator.csproj --no-restore /p:Version=${{env.APP_VERSION}} --configuration Release --output ${{env.RELEASE_PATH}}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: v${{env.APP_VERSION}}
        release_name: Release v${{env.APP_VERSION}}
        draft: false
        prerelease: false
        body: |
          Defaults:
          --manifest-path=https://raw.githubusercontent.com/dannydwarren/machine-configs/main/manifests/test.manifest.json
          --environments=Test
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: ${{env.RELEASE_PATH}}/Configurator.exe
        asset_name: Configurator.exe
        asset_content_type: application/vnd.microsoft.portable-executable